name: Generate PDF

on:
  push:

jobs:
  run-tectonic:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Tectonic cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-tectonic-

      - name: Install tectonic
        uses: wtfjoke/setup-tectonic@v4

      - name: Run tectonic
        run: tectonic -X build

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: build/default/default.pdf

      - name: Make folder for pages
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir public
          cp build/default/default.pdf "public/BUM Standard.pdf"

      - name: Deploy to github pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public

      - name: Prepare PDF for release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          cp build/default/default.pdf "BUM Standard ${GITHUB_REF_NAME}.pdf"

      - name: Release PDF
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: build/default/default.pdf
