name: Generate PDF

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install tectonic
        uses: wtfjoke/setup-tectonic@v4

      - name: Run tectonic
        run: tectonic -X build

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: build/default/default.pdf
